name: 🐛 Bug Report
description: Report a bug or issue with Beast Mode Social Creator
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: input
    id: aspire-version
    attributes:
      label: .NET Aspire Version
      description: What version of .NET Aspire are you using?
      placeholder: "9.4.0"
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What version of .NET are you using?
      placeholder: "9.0.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - AppHost Orchestration
        - Web UI (Blazor)
        - API Service
        - Content Processor
        - Platform Integration
        - Analytics Service
        - Azure Functions
        - Service Defaults
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'dotnet run --project SocialContentCreator.AppHost'
        2. Navigate to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or stack traces
      render: text

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: Windows 11
        - Docker: Docker Desktop 4.x
        - IDE: Visual Studio 2022 / VS Code
        - Browser: Chrome/Edge/Firefox (if UI related)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
