name: ✨ Feature Request
description: Suggest a new feature or enhancement for Beast Mode Social Creator
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - AI/Content Generation
        - Social Media Integration
        - User Interface/UX
        - Analytics/Reporting
        - Performance/Optimization
        - Security/Authentication
        - DevOps/Deployment
        - API/Backend
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: examples
    attributes:
      label: Examples/References
      description: Are there any existing implementations or examples you can reference?
      placeholder: Links to similar features, mockups, or reference implementations...

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation ideas
      placeholder: |
        - Integration with Azure OpenAI
        - Database schema changes
        - API endpoints needed
        - UI components required
        - Performance implications

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas of the application would this feature affect?
      options:
        - label: AppHost Configuration
        - label: Web UI (Blazor)
        - label: API Services
        - label: Database Schema
        - label: Azure Integration
        - label: Performance
        - label: Security
        - label: Documentation
        - label: Testing

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.
